spring:
  application:
    name: Config-Server-Development
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
